<?php

namespace App\Transformers;

use Illuminate\Http\Resources\Json\JsonResource;

class DataMemberTransformers extends JsonResource
{
    public function toArray($request)
    { 
        return [
            "kode_cabang" => $this->cus_kodeigr,
            "kode_member" => $this->cus_kodemember,
            "nama" => $this->cus_namamember,
            "alamat_surat" => $this->cus_alamatmember1,
            "kota" => $this->cus_alamatmember2,
            "kode_pos" => $this->cus_alamatmember3,
            "kelurahan" => $this->cus_alamatmember4,
            "alamat_ktp" => $this->cus_alamatmember5,
            "kota_ktp" => $this->cus_alamatmember6,
            "kode_pos_ktp" => $this->cus_alamatmember7,
            "kelurahan_ktp" => $this->cus_alamatmember8,
            "no_ktp" => $this->cus_noktp,
            "no_hp" => $this->cus_hpmember,
            "tgl_lahir" => $this->cus_tgllahir,
            "jenis_outlet" => $this->cus_kodeoutlet,
            "sub_outlet" => $this->cus_kodesuboutlet,
            "pkp" => $this->cus_flagpkp,
            "area" => $this->cus_kodearea,
            "telepon" => $this->cus_tlpmember,
            "kredit" => $this->cus_flagkredit,
            "top" => $this->cus_top,
            "jenis_cust" => $this->cus_jenismember?$this->cus_jenismember:0,
            "bebas_iuran" => $this->cus_flagbebasiuran,
            "retail_khusus" => $this->cus_flagmemberkhusus,
            "ganti_kartu" => $this->cus_flaggantikartu,
            "jarak" => $this->cus_jarak,
            "limit" => $this->cus_creditlimit,
            "npwp" => $this->cus_npwp,
            "blocking_pengiriman" => $this->cus_flagblockingpengiriman,
            "salesman" => $this->cus_nosalesman,
            "alamat_email" => $this->cus_alamatemail,

            //========= all columnt no defined===========//

            "cus_kodeigr" => $this->cus_kodeigr,
            "cus_recordid" => $this->cus_recordid,
            "cus_kodemember" => $this->cus_kodemember,
            "cus_namamember" => $this->cus_namamember,
            "cus_alamatmember1" => $this->cus_alamatmember1,
            "cus_alamatmember2" => $this->cus_alamatmember2,
            "cus_alamatmember3" => $this->cus_alamatmember3,
            "cus_alamatmember4" => $this->cus_alamatmember4,
            "cus_tlpmember" => $this->cus_tlpmember,
            "cus_alamatmember5" => $this->cus_alamatmember5,
            "cus_alamatmember6" => $this->cus_alamatmember6,
            "cus_alamatmember7" => $this->cus_alamatmember7,
            "cus_alamatmember8" => $this->cus_alamatmember8,
            "cus_jenismember" => $this->cus_jenismember,
            "cus_flagmemberkhusus" => $this->cus_flagmemberkhusus,
            "cus_jarak" => $this->cus_jarak,
            "cus_cfk" => $this->cus_cfk,
            "cus_kodeoutlet" => $this->cus_kodeoutlet,
            "cus_kodesuboutlet" => $this->cus_kodesuboutlet,
            "cus_kodearea" => $this->cus_kodearea,
            "cus_tglmulai" => $this->cus_tglmulai,
            "cus_tglregistrasi" => $this->cus_tglregistrasi,
            "cus_npwp" => $this->cus_npwp,
            "cus_flagpkp" => $this->cus_flagpkp,
            "cus_creditlimit" => $this->cus_creditlimit,
            "cus_top" => $this->cus_top,
            "cus_keterangan" => $this->cus_keterangan,
            "cus_tglpajak" => $this->cus_tglpajak,
            "cus_nosalesman" => $this->cus_nosalesman,
            "cus_flaggantikartu" => $this->cus_flaggantikartu,
            "cus_nokartumember" => $this->cus_nokartumember,
            "cus_flagkredit" => $this->cus_flagkredit,
            "cus_flagblockingpengiriman" => $this->cus_flagblockingpengiriman,
            "cus_flagbebasiuran" => $this->cus_flagbebasiuran,
            "cus_tgllahir" => $this->cus_tgllahir,
            "cus_costcenter" => $this->cus_costcenter,
            "cus_noaccount" => $this->cus_noaccount,
            "cus_alamatemail" => $this->cus_alamatemail,
            "cus_hpmember" => $this->cus_hpmember,
            "cus_flaginstitusipemerintah" => $this->cus_flaginstitusipemerintah,
            "cus_create_by" => $this->cus_create_by,
            "cus_create_dt" => $this->cus_create_dt,
            "cus_modify_by" => $this->cus_modify_by,
            "cus_modify_dt" => $this->cus_modify_dt,
            "cus_getpoint" => $this->cus_getpoint,
            "cus_flagkirimsms" => $this->cus_flagkirimsms,
            "cus_flag_uptodate" => $this->cus_flag_uptodate,
            "cus_nonaktif_dt" => $this->cus_nonaktif_dt,
            "cus_flag_ina" => $this->cus_flag_ina,
            "cus_tglmulai_va" => $this->cus_tglmulai_va,
            "cus_noacc_va" => $this->cus_noacc_va,
            "cus_noktp" => $this->cus_noktp,
            "cus_flag_verifikasi" => $this->cus_flag_verifikasi,
            "cus_flag_mypoin" => $this->cus_flag_mypoin,
            "cus_flag_isaku" => $this->cus_flag_isaku,
            "cus_mypoin_dt" => $this->cus_mypoin_dt,
            "cus_isaku_dt" => $this->cus_isaku_dt,
            "cus_jenismember_isaku" => $this->cus_jenismember_isaku,
            "cus_flag_spi" => $this->cus_flag_spi,
            "cus_namaktp" => $this->cus_namaktp,
            "cus_flagdaftarklik" => $this->cus_flagdaftarklik,
            "cus_flag_ifs" => $this->cus_flag_ifs,
            "cus_flag_kummandiri" => $this->cus_flag_kummandiri,
            "cus_flag_supplier" => $this->cus_flag_supplier,
            "rnum" => $this->rnum,
        ];
    }
}